server:
  port: 8991

github:
  client:
    id: a2fe7261bc5ed91a27d8
    sercet: 4474eedbc2e31b7c6f0f2349d1b9e074c8b1f10a
  redirect:
    url: http://localhost:8991/callback
spring:
  datasource:
    username: li
    password: 123456
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/tan
