server:
  port: 8991

github:
  client:
    id: a2fe7261bc5ed91a27d8
    sercet: 2b66b95c812a1dfd59b00d2294fb78fe5480498a
  redirect:
    url: http://localhost:8991/callback
spring:
  datasource:
    username: li
    password: 123456
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/tan
